# Experiment 1.A - BFS (Breadth First Search)

## AIM
To implement Breadth First Search traversal for a graph.

## ALGORITHM
1. Start by putting any one of the graph's vertices at the back of a queue.
2. Take the front item of the queue and add it to the visited list.
3. Create a list of that vertex's adjacent nodes. Add the ones which aren't in the visited list to the back of the queue.
4. Keep repeating steps 2 and 3 until the queue is empty.




In [22]:
from ds import Graph, Queue

def bfs(grph: Graph, vrt):
    """
    The algorithm works as follows:
        1. Start by putting any one of the graph's vertices at the back of a queue.
        2. Take the front item of the queue and add it to the visited list.
        3. Create a list of that vertex's adjacent nodes. Add the ones which aren't in the visited list to the back of the queue.
        4. Keep repeating steps 2 and 3 until the queue is empty.
    """

    if not grph.isVertice(vrt):
        return None
    q = Queue()
    q.enQueue(vrt)
    visited = []
    while not q.isEmpty():
        vrtx = q.deQueue()
        # print(vrtx,end="\t")
        visited.append(vrtx)
        neibours = grph.edgesOf(vrtx)
        # print(neibours, visited)
        for neibour in neibours:
            if not (neibour in visited) and not q.inQueue(neibour):
                q.enQueue(neibour)
            else:
                continue
        # q.display()
    return visited

G = Graph(graph={0: [1, 2, 3], 1: [0, 2], 2: [0, 4], 3: [1], 4: [2]})
G.Print_adjList()

bfs = bfs(G, 1)
print(bfs)


Adjcent List:
--------------------
0 : [1, 2, 3]
1 : [0, 2]
2 : [0, 4]
3 : [1]
4 : [2]
--------------------
[1, 0, 2, 3, 4]


## RESULT
Hence BFS has been implemented and the graph has been traversed successfully

# Experiment 1.B - DFS (DEPTH FIRST SEARCH)

## AIM
To implement DFS traversal for a graph.

## ALGORITHM
1. Start by putting any one of the graph's vertices at the back of a queue.
2. Take the front item of the queue and add it to the visited list.
3. Create a list of that vertex's adjacent nodes. Add the ones which aren't in the visited list to the back of the queue.
4. Keep repeating steps 2 and 3 until the queue is empty.




In [23]:
from ds import Stack, Graph


def dfs(G: Graph, starting_vertex):
    if not G.isVertice(starting_vertex):
        return None
    visited = set()
    stk = Stack()
    stk.push(starting_vertex)
    visited.add(starting_vertex)
    while not stk.isEmpty():
        vertx = stk.top()
        h = (set(G.edgesOf(vertx)) - visited)
        if len(h) == 0:
            print(stk.pop())
        else:
            adj = list(h)[0]
            visited.add(adj)
            stk.push(adj)



G = Graph(graph={1: [2, 3], 2: [1, 4, 5], 3: [1, 4], 4: [2, 3, 5], 5: [2, 4]})

G.Print_adjList()


DFS = dfs(G, 1)
print(DFS)


Adjcent List:
--------------------
1 : [2, 3]
2 : [1, 4, 5]
3 : [1, 4]
4 : [2, 3, 5]
5 : [2, 4]
--------------------
3
5
4
2
1
None


## RESULT
 Hence DFS has been implemented and the graph has been traversed successfully

# Experiment 2 - Implementing MST using Prim’s Algorithm

## AIM
To implement Prim’s algorithm for finding the Minimum Spanning Tree (MST) of a graph.

## ALGORITHM
1. **Initialization**:
   - Initialize the required data structures and set the initial vertex as visited.

2. **Main Loop**:
   - Continue the algorithm until all vertices are visited. This loop is based on the number of visited vertices compared to the total number of vertices in the graph (n).

3. **Find Minimum-Weight Edge**:
   - Identify the minimum-weight edge connected to the visited vertices by examining and sorting all edges based on their weights.

4. **Cycle Check**:
   - Ensure that the selected edge does not create a cycle in the MST by verifying that both of its vertices are not already visited.

5. **Update MST and Mark Vertices**:
   - If the edge does not create a cycle, add it to the MST and mark its vertices as visited.
   - Yield the current minimum-weight edge as part of the MST.


In [24]:
from weight_Graph import Graph

def prim(G: Graph, vertex):
    n = G.numberOfVertices()
    visited_vertice = set()
    visited_edges = set()
    visited_vertice.add(vertex)
    while len(visited_vertice) != n:
        cur_edge = []
        for a in visited_vertice:
            cur_edge += G.edgesOf(a, n=True)

        cur_edge = list(sorted(cur_edge, key=lambda x: x[-1]))
        while (cur_edge[0][1] in visited_vertice and cur_edge[0][0] in visited_vertice):
            cur_edge.pop(0)

        v1 = cur_edge[0][0]
        v2 = cur_edge[0][1]
        w = cur_edge[0][-1]
        visited_edges.add((v1, v2, w))
        visited_edges.add((v2, v1, w))

        # to say no cycle
        if not (v2 in visited_vertice and v1 in visited_vertice):
            visited_vertice.add(v2)
            visited_vertice.add(v1)
            yield cur_edge[0]


G = Graph()

if __name__ == '__main__':
    G.add_vertice("A")
    G.add_vertice("B")
    G.add_vertice("C")
    G.add_vertice("D")
    G.add_vertice("E")
    G.add_vertice("F")

    G.add_edge("A", "B", 4, un=True)
    G.add_edge("A", "C", 4, un=True)
    G.add_edge("B", "C", 2, un=True)

    G.add_edge("C", "D", 3, un=True)
    G.add_edge("D", "F", 3, un=True)
    G.add_edge("C", "F", 4, un=True)
    G.add_edge("C", "E", 2, un=True)
    G.add_edge("E", "F", 3, un=True)

    # G.Print_adjMat()
    # G.Print_adjList()
    # print(G.allEdges(un = True))
    pt = prim(G, "F")
    print(list(pt), sep="\n")

[('F', 'D', 3), ('F', 'E', 3), ('E', 'C', 2), ('C', 'B', 2), ('B', 'A', 4)]


# Experiment 3 - Implementing MST using Kruskal’s Algorithm

## AIM
To implement Kruskal’s algorithm for finding the Minimum Spanning Tree (MST) of a graph.

## ALGORITHM
1. **Initialization**:
   - Set up data structures, including a list of all edges, a Disjoint Set data structure, and sets to track visited edges and vertices.

2. **Sorting Edges**:
   - Sort all edges in ascending order based on their weights.

3. **Main Loop**:
   - Continue the algorithm until all vertices are visited. The loop stops when the number of visited vertices equals the total number of vertices.

4. **Select Minimum Edge**:
   - Pick the minimum-weight edge (greedy choice) from the sorted list of edges.

5. **Edge Validation and Update**:
   - Check if adding the edge creates a cycle, and if not, yield the edge as part of the MST.
   - Update the sets of visited edges and vertices, remove the reverse edge, and perform a union operation to merge the sets of the connected vertices.

This algorithm constructs the Minimum Spanning Tree of the given graph by iteratively selecting and validating edges based on their weights.


In [25]:
from weight_Graph import Graph
from ds import DisjointSet


def kruskal(G: Graph):
    edges = G.allEdges()
    disSet = DisjointSet(G.Vertices())
    n = G.numberOfVertices()
    visted_edges = set()
    visted_vertices = set()
    edges.sort(key=lambda x: x[-1])
    #while n-1 != len(visted_edges):
    while n != len(visted_vertices):
        min_ = edges.pop(0)
        if not (min_ in visted_edges and (min_[1], min_[0], min_[-1]) in visted_edges) and (disSet.find(min_[0]) != disSet.find(min_[1])):
            yield min_
            visted_edges.add(min_)
            visted_edges.add((min_[1], min_[0], min_[-1]))
            edges.remove((min_[1], min_[0], min_[-1]))
            disSet.union(min_[0], min_[1])
            visted_vertices.add(min_[0])
            visted_vertices.add(min_[1])


G = Graph()

if __name__ == '__main__':
    G.add_vertice("A")
    G.add_vertice("B")
    G.add_vertice("C")
    G.add_vertice("D")
    G.add_vertice("E")
    G.add_vertice("F")

    G.add_edge("A", "B", 4, un=True)
    G.add_edge("A", "C", 4, un=True)
    G.add_edge("B", "C", 2, un=True)

    G.add_edge("C", "D", 3, un=True)
    G.add_edge("D", "F", 3, un=True)
    G.add_edge("C", "F", 4, un=True)
    G.add_edge("C", "E", 2, un=True)
    G.add_edge("E", "F", 3, un=True)

    k = list(kruskal(G))
    print(k, sep="\n")


[('B', 'C', 2), ('C', 'E', 2), ('C', 'D', 3), ('D', 'F', 3), ('A', 'B', 4)]


# EXPERIMENT 4
### Standard Implementations of Numpy Library

#### NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries.


## Installation Instructions

in anaconda

    conda install numpy

in pip

    pip install numpy

## Using NumPy

Once you've installed NumPy you can import it as a library:

### Numpy Arrays




## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [26]:
import numpy as np

my_list = [1,2,3]
print(my_list,type(my_list))
arr =  np.array(my_list)
print(arr, type(arr))

my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
print(my_matrix,type(my_matrix))
np_matrix = np.array(my_matrix)
print(np_matrix,type(np_matrix))

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>
[[1, 2, 3], [4, 5, 6], [7, 8, 9]] <class 'list'>
[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'>


### Replicating, joining, or mutating existing arrays


In [27]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a[:2]
b += 1
print('a =', a, '; b =', b)

a = [2 3 3 4 5 6] ; b = [2 3]


In this example, you did not create a new array. You created a variable, b that viewed the first 2 elements of a. When you added 1 to b you would get the same result by adding 1 to a[:2].
If you want to create a new array, use the numpy.copy array creation routine as such:

In [28]:
a = np.array([1, 2, 3, 4])
b = a[:2].copy()
b += 1
print('a = ', a, 'b = ', b)

a =  [1 2 3 4] b =  [2 3]


## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [29]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros , ones, diags

Generate arrays of zeros ,ones , diags

In [31]:
np.zeros(3)

array([0., 0., 0.])

In [32]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
np.ones(3)

array([1., 1., 1.])

In [34]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [35]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [36]:
np.diag([1, 2, 3], 1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [37]:
a = np.array([[1, 2], [3, 4]])
np.diag(a)

array([1, 4])

### linspace
Return evenly spaced numbers over a specified interval.

In [38]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [39]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [40]:
np.random.randint(1,100)

38

In [41]:
np.random.randint(1,100,10)

array([49, 27, 50,  5, 52,  9, 74, 23, 69,  7])

## Reshape, flatten 
Returns an array containing the same data with a new shape.

In [42]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [43]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [45]:
arr.shape

(25,)

### max,min

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [46]:
arr.max()

24

In [47]:
arr.min()

0

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [48]:
import numpy as np
arr = np.arange(0,10)
arr2 = np.arange(0,20,2) 
print(arr)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]


In [49]:
arr + arr2

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [50]:
arr2 * arr

array([  0,   2,   8,  18,  32,  50,  72,  98, 128, 162])

In [51]:
arr2 - arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr2/arr

C:\Users\gurup\AppData\Local\Temp\ipykernel_2992\209023188.py:3: RuntimeWarning: invalid value encountered in divide
  arr2/arr


array([nan,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.])

In [53]:
# Also warning, but not an error instead infinity
1/arr

C:\Users\gurup\AppData\Local\Temp\ipykernel_2992\1360216608.py:2: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [54]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [55]:
#Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [56]:
#Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [57]:
np.max(arr) #same as arr.max()

9

In [58]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [59]:
np.log(arr)

C:\Users\gurup\AppData\Local\Temp\ipykernel_2992\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

### NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [60]:
#Creating sample array
arr1 = np.arange(0,11)

In [61]:
#Show
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [62]:
#Get a value at an index
arr1[8]

8

In [63]:
#Get values in a range
arr1[1:5]

array([1, 2, 3, 4])

In [64]:
#Get values in a range
arr1[0:5]

array([0, 1, 2, 3, 4])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [65]:
#Setting a value with index range (Broadcasting)
arr1[0:5]=100

#Show
arr1

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [66]:
# Reset array, we'll see why I had to reset in  a moment
arr1 = np.arange(0,11)

#Show
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
#Important notes on Slices
slice_of_arr1 = arr1[0:6]

#Show slice
slice_of_arr1

array([0, 1, 2, 3, 4, 5])

In [68]:
#Change Slice
slice_of_arr1[:]=99

#Show Slice again
slice_of_arr1

array([99, 99, 99, 99, 99, 99])

Now note the changes also occur in our original array!

In [69]:
arr1

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [70]:
#To get a copy, need to be explicit
arr1_copy = arr1.copy()

arr1_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**.

In [71]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [72]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [73]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [74]:
# Getting individual element value
arr_2d[1,0]

20

In [75]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [76]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [77]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [78]:
#Set up matrix
arr2d = np.zeros((10,10))

In [79]:
#Length of array
arr_length = arr2d.shape[1]

In [80]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

Fancy indexing allows the following

In [81]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [82]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [83]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [84]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [85]:
bool_arr = arr>4

In [86]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [87]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [88]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [89]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

#

# Experiment 5 - Tries Implementation

## AIM
To write a Python program to implement Tries.

## ALGORITHM

1. **Create a Recursive Function**:
   - Develop a recursive function that takes a node and a string as input.

2. **Base Case - Empty String**:
   - If the string is empty, mark the current node as a leaf node and return. This indicates the end of a word or string.

3. **Check for Child Node**:
   - If the string is not empty, get the first character of the string.
   - Check if the current node has a child for that character.

4. **Child Node Existence**:
   - If a child node exists for the character, move to the child node and recursively call the function with the remaining characters of the string.

5. **Create New Child Node**:
   - If there's no child node for the character, create a new child node for that character and then recursively call the function with the remaining characters of the string.


In [94]:
class TrieNode:
    def __init__(self):
        self.children = {}
        self.is_end_of_word = False

def insert(root, word):
    node = root
    for char in word:
        if char not in node.children:
            node.children[char] = TrieNode()
        node = node.children[char]
    node.is_end_of_word = True

def search(root, word):
    node = root
    for char in word:
        if char not in node.children:
            return False
        node = node.children[char]
    return node.is_end_of_word
def print_trie(root, prefix=""):
    if root.is_end_of_word:
        print(prefix)
    for char, node in root.children.items():
        print_trie(node, prefix + char)

# Example Usage:
root = TrieNode()
words = ["apple", "app", "apricot", "banana", "bat"]
for word in words:
    insert(root, word)
print_trie(root)
print()
print(search(root, "apple"))  # Output: True
print(search(root, "apples"))  # Output: False

app
apple
apricot
banana
bat

True
False


# Experiment 6 - Radix Sort Implementation

## AIM
To write a Python program to implement Radix Sort.

## ALGORITHM
1. **Initialization**: Find the maximum number in the array and determine the number of digits in it.

2. **Create Buckets**: Create 10 buckets (0-9), one for each digit.

3. **Iterate through Digits**: For each digit, from the least significant to the most significant:
   - Place numbers into buckets based on the current digit.
   - Reconstruct the array by emptying the buckets in order.

4. **Repeat for Each Digit**: Python's ability to create nested loops makes it easy to repeat the process for each digit from the least significant to the most significant.

5. **Completion**: After processing all digits, the array is sorted, and you have the sorted result.

This experiment demonstrates the implementation of Radix Sort in Python, a non-comparative sorting algorithm that sorts numbers by processing their digits from least significant to most significant.


In [90]:
l=eval(input("enter array in format [123,1323,134,52] : "))
d={0:[],1:[],2:[],3:[],4:[],5:[],6:[],7:[],8:[],9:[]}
digits=len(str(max(l)))
mod=10
for i in range(digits):
    new_l=[]
    for j in l:
        nl=d[(j%mod)//(mod/10)]
        nl.append(j)
    for j in d.values():
        new_l+=j
        j.clear()
    l=new_l
    mod*=10
    print("round",i)
    print(l)

round 0
[52, 123, 1323, 134]
round 1
[123, 1323, 134, 52]
round 2
[52, 123, 134, 1323]
round 3
[52, 123, 134, 1323]


# Experiment 7 - SHA-256 Implementation

## AIM
To write a Python program to implement SHA-256.

## ALGORITHM

1. **Encode the Input String**:
   - Convert the input string to a byte array using the `encode()` method. This ensures that the input data is in a format that can be processed by the SHA-256 algorithm.

2. **Hash the Byte Array**:
   - Use the `sha256()` function from a cryptography library (e.g., `hashlib` in Python) to hash the byte array.
   - The `sha256()` function takes the byte array as input and calculates the SHA-256 hash.

3. **Get the Hexadecimal Digest**:
   - Convert the hash obtained in step 2 to a hexadecimal string using the `hexdigest()` method. This provides a human-readable representation of the hash.
   - The hexadecimal digest is the final output of the SHA-256 process.

This experiment demonstrates the implementation of SHA-256 in Python to calculate the hash of an input string and obtain its hexadecimal digest.

In [91]:
from hashlib import sha256

string = "this is fun"

hs = sha256(str.encode("utf - 8")).hexdigest()
print(hs)

65768cb7d1407bda3159de800d13f4ba1754adf024f304a4609422a430be47a6


# Experiment 8 - Merkle Trees

## AIM
To write a Python program to implement Merkle trees.

## ALGORITHM
1. **Initialize Merkle Tree with Data**:
   - Start with a set of data blocks.

2. **Build Merkle Tree Recursively**:
   - Build the Merkle tree recursively by grouping data blocks into pairs.
   - For each pair of data blocks, calculate a hash (e.g., SHA-256) of the concatenation of the hashes of the two blocks.
   - Continue this process until you have a single root hash, which represents the entire set of data blocks.

3. **Get Root Hash of Merkle Tree**:
   - The root hash obtained in step 2 represents the entire set of data.
   - This root hash is used to verify the integrity of the data.

4. **Verify Merkle Tree with Data and Root Hash**:
   - To verify the integrity of data, reconstruct the Merkle tree as in step 2.
   - Compare the root hash calculated in this step with the root hash obtained earlier.
   - If they match, the data is considered intact and has not been tampered with.

5. **Use Merkle Tree to Verify Integrity of Data**:
   - Given a set of data blocks and their corresponding Merkle tree, you can use the tree to efficiently verify the integrity of any specific data block.
   - To verify a data block, start with its hash and trace its path up the tree to the root, calculating and comparing hashes at each step.
   - If the calculated hash matches the root hash, the data block is verified as authentic.

This experiment demonstrates the implementation and use of Merkle trees to verify data integrity efficiently.


In [92]:
import hashlib

# Function to compute the SHA-256 hash of a string
def SHA(data):
    sha256 = hashlib.sha256()
    sha256.update(data.encode('utf-8'))
    return sha256.hexdigest()

# Function to build a Merkle Tree from a list of data items and print the full tree
def buildAndPrintMerkleTree(data):
    if not data:
        return None

    currentLayer = data
    fullTree = [currentLayer]  # To store all levels of the tree

    while len(currentLayer) > 1:
        newLayer = []

        for i in range(0, len(currentLayer), 2):
            combinedHash = currentLayer[i]
            if i + 1 < len(currentLayer):
                combinedHash += currentLayer[i + 1]

            newLayer.append(SHA(combinedHash))

        currentLayer = newLayer
        fullTree.append(currentLayer)

    return fullTree

# Function to print the Merkle Tree
def printMerkleTree(tree):
    for level, hashes in enumerate(tree):
        print(f"Level {level}:")
        for i, hash in enumerate(hashes):
            print(f"\tNode {i}: {hash}")
        print()

# Example usage:
data = ["123", "456", "789", "324"]

fullTree = buildAndPrintMerkleTree(data)
print("Merkle Root:", fullTree[-1][0])  # Merkle Root is the last element

# Print the full tree
print("\nFull Merkle Tree:")
printMerkleTree(fullTree)

Merkle Root: d28b37a1683dadcf959c78c5c8e68694cbe28d87a61ba8c26d16adcd1a2d8fb7

Full Merkle Tree:
Level 0:
	Node 0: 123
	Node 1: 456
	Node 2: 789
	Node 3: 324

Level 1:
	Node 0: 8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92
	Node 1: 09fd7f0815b321ac516da995d3b95c6340ddb2401b8dc437d1733638c7132ba4

Level 2:
	Node 0: d28b37a1683dadcf959c78c5c8e68694cbe28d87a61ba8c26d16adcd1a2d8fb7



# Experiment 9 - Fusion Tree

## AIM
To gain a deep understanding of Fusion Trees.

## FUSION TREE
- A fusion tree is a tree data structure that implements an associative array on w-bit integers. It's designed to store integers that fit into a single machine word.
- For example, on a 32-bit machine, you can use a fusion tree to store integers of up to 32 bits.
- Fusion trees are used to solve the predecessor and successor problem.
- They use O(n) space and perform searches on a collection of n key–value pairs.
- They can perform sketch, parallel comparison, predecessor and successor, and insert operations in O(log N) time and O(N) space complexity.
- Fusion trees are a powerful data structure that can be used to store and access associative arrays efficiently.
- They are especially well-suited for applications where speed is important, such as real-time systems and databases.

## RESULT
Hence, Fusion trees have been studied effectively.

This experiment provides an overview of Fusion Trees, their capabilities, and their relevance in solving problems related to associative arrays efficiently.
