# EXPERIMENT 4
### Standard Implementations of Numpy Library

#### NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries.


## Installation Instructions

in anaconda

    conda install numpy

in pip

    pip install numpy

## Using NumPy

Once you've installed NumPy you can import it as a library:

### Numpy Arrays




## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [26]:
import numpy as np

my_list = [1,2,3]
print(my_list,type(my_list))
arr =  np.array(my_list)
print(arr, type(arr))

my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
print(my_matrix,type(my_matrix))
np_matrix = np.array(my_matrix)
print(np_matrix,type(np_matrix))

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>
[[1, 2, 3], [4, 5, 6], [7, 8, 9]] <class 'list'>
[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'>


### Replicating, joining, or mutating existing arrays


In [27]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a[:2]
b += 1
print('a =', a, '; b =', b)

a = [2 3 3 4 5 6] ; b = [2 3]


In this example, you did not create a new array. You created a variable, b that viewed the first 2 elements of a. When you added 1 to b you would get the same result by adding 1 to a[:2].
If you want to create a new array, use the numpy.copy array creation routine as such:

In [28]:
a = np.array([1, 2, 3, 4])
b = a[:2].copy()
b += 1
print('a = ', a, 'b = ', b)

a =  [1 2 3 4] b =  [2 3]


## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [29]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros , ones, diags

Generate arrays of zeros ,ones , diags

In [31]:
np.zeros(3)

array([0., 0., 0.])

In [32]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
np.ones(3)

array([1., 1., 1.])

In [34]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [35]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [36]:
np.diag([1, 2, 3], 1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [37]:
a = np.array([[1, 2], [3, 4]])
np.diag(a)

array([1, 4])

### linspace
Return evenly spaced numbers over a specified interval.

In [38]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [39]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [40]:
np.random.randint(1,100)

38

In [41]:
np.random.randint(1,100,10)

array([49, 27, 50,  5, 52,  9, 74, 23, 69,  7])

## Reshape, flatten 
Returns an array containing the same data with a new shape.

In [42]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [43]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [45]:
arr.shape

(25,)

### max,min

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [46]:
arr.max()

24

In [47]:
arr.min()

0

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [48]:
import numpy as np
arr = np.arange(0,10)
arr2 = np.arange(0,20,2) 
print(arr)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]


In [49]:
arr + arr2

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [50]:
arr2 * arr

array([  0,   2,   8,  18,  32,  50,  72,  98, 128, 162])

In [51]:
arr2 - arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr2/arr

C:\Users\gurup\AppData\Local\Temp\ipykernel_2992\209023188.py:3: RuntimeWarning: invalid value encountered in divide
  arr2/arr


array([nan,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.])

In [53]:
# Also warning, but not an error instead infinity
1/arr

C:\Users\gurup\AppData\Local\Temp\ipykernel_2992\1360216608.py:2: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [54]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [55]:
#Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [56]:
#Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [57]:
np.max(arr) #same as arr.max()

9

In [58]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [59]:
np.log(arr)

C:\Users\gurup\AppData\Local\Temp\ipykernel_2992\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

### NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [60]:
#Creating sample array
arr1 = np.arange(0,11)

In [61]:
#Show
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [62]:
#Get a value at an index
arr1[8]

8

In [63]:
#Get values in a range
arr1[1:5]

array([1, 2, 3, 4])

In [64]:
#Get values in a range
arr1[0:5]

array([0, 1, 2, 3, 4])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [65]:
#Setting a value with index range (Broadcasting)
arr1[0:5]=100

#Show
arr1

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [66]:
# Reset array, we'll see why I had to reset in  a moment
arr1 = np.arange(0,11)

#Show
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
#Important notes on Slices
slice_of_arr1 = arr1[0:6]

#Show slice
slice_of_arr1

array([0, 1, 2, 3, 4, 5])

In [68]:
#Change Slice
slice_of_arr1[:]=99

#Show Slice again
slice_of_arr1

array([99, 99, 99, 99, 99, 99])

Now note the changes also occur in our original array!

In [69]:
arr1

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [70]:
#To get a copy, need to be explicit
arr1_copy = arr1.copy()

arr1_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**.

In [71]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [72]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [73]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [74]:
# Getting individual element value
arr_2d[1,0]

20

In [75]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [76]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [77]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [78]:
#Set up matrix
arr2d = np.zeros((10,10))

In [79]:
#Length of array
arr_length = arr2d.shape[1]

In [80]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

Fancy indexing allows the following

In [81]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [82]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [83]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [84]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [85]:
bool_arr = arr>4

In [86]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [87]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [88]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [89]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

#